import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Button } from '@/components/ui/button';
import { FileDown, ArrowLeft, ZoomIn } from 'lucide-react';
import designTree from '@/assets/design-tree.png';
import designMandala from '@/assets/design-mandala.png';
import designWaves from '@/assets/design-waves.png';

export const designs = [
  { 
    id: 'tree-of-life',
    title: 'Tree of Life', 
    category: 'Nature', 
    image: designTree, 
    desc: 'Intricate branches and roots representing unity and growth.',
    technical: 'Best for: 1.5mm - 3mm Stainless Steel or Acrylic.',
    size: 'Standard size: 600mm x 600mm'
  },
  { 
    id: 'golden-mandala',
    title: 'Golden Mandala', 
    category: 'Geometric', 
    image: designMandala, 
    desc: 'Complex geometric patterns perfect for wall decor or lighting fixtures.',
    technical: 'Best for: 1mm - 2mm Brass or Powder-coated mild steel.',
    size: 'Standard size: 800mm x 800mm'
  },
  { 
    id: 'modern-waves',
    title: 'Modern Waves', 
    category: 'Abstract', 
    image: designWaves, 
    desc: 'Abstract wave patterns suitable for privacy screens and room dividers.',
    technical: 'Best for: 2.5mm+ Aluminum or Wood.',
    size: 'Standard size: 1200mm x 2400mm'
  },
];

import { jsPDF } from 'jspdf';

const DesignDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const design = designs.find(d => d.id === id);

  if (!design) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4">Design Not Found</h1>
          <Button onClick={() => navigate('/design-library')}>Back to Library</Button>
        </div>
      </div>
    );
  }

  const handleDownload = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(30, 95, 52); // Brand primary color (approx)
    doc.text('BIKANER LASER', 20, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(100, 100, 100);
    doc.text('Design Specification', 20, 30);
    
    // Content
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 35, 190, 35);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(`Title: ${design.title}`, 20, 50);
    doc.text(`Category: ${design.category}`, 20, 60);
    
    doc.setFont('helvetica', 'normal');
    doc.text('Description:', 20, 75);
    doc.text(doc.splitTextToSize(design.desc, 170), 20, 85);
    
    doc.setFont('helvetica', 'bold');
    doc.text('Technical Details:', 20, 110);
    doc.setFont('helvetica', 'normal');
    doc.text(design.technical, 20, 120);
    doc.text(design.size, 20, 130);
    
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Bikaner Laser Design Tool', 20, 280);
    doc.text('Visit us at bikanerlaser.com', 20, 285);
    
    doc.save(`${design.id}-specification.pdf`);
  };

  return (
    <div className="bg-background min-h-screen">
      <Navbar />
      <div className="pt-32 pb-20 px-6 lg:px-12 max-w-7xl mx-auto">
        <motion.button
          onClick={() => navigate('/design-library')}
          className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors mb-12 group"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
        >
          <ArrowLeft size={18} className="group-hover:-translate-x-1 transition-transform" />
          Back to Library
        </motion.button>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
          {/* Image Display */}
          <motion.div 
            className="rounded-3xl overflow-hidden bg-card border border-border group relative aspect-square"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
          >
            <img 
              src={design.image} 
              alt={design.title} 
              className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110"
            />
            <div className="absolute inset-0 bg-black/5 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
              <ZoomIn className="text-white h-12 w-12" />
            </div>
          </motion.div>

          {/* Details Content */}
          <motion.div
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            <span className="font-body text-sm tracking-[0.3em] uppercase text-primary font-medium block mb-4">
              {design.category} Design
            </span>
            <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
              {design.title}
            </h1>
            
            <p className="font-body text-lg text-muted-foreground mb-8 leading-relaxed">
              {design.desc}
            </p>

            <div className="space-y-6 mb-12">
              <div className="p-6 rounded-2xl bg-muted/30 border border-border">
                <h3 className="font-display font-bold text-lg mb-2">Technical Specifications</h3>
                <p className="font-body text-sm text-foreground/80">{design.technical}</p>
                <p className="font-body text-sm text-foreground/80 mt-1">{design.size}</p>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <Button 
                onClick={handleDownload}
                className="py-7 px-10 rounded-2xl flex items-center gap-3 text-lg font-bold shadow-xl shadow-primary/20"
              >
                <FileDown className="h-5 w-5" />
                Download PDF
              </Button>
              <Button 
                variant="outline"
                onClick={() => navigate('/#contact')}
                className="py-7 px-10 rounded-2xl text-lg font-bold"
              >
                Inquire about this design
              </Button>
            </div>
          </motion.div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default DesignDetail;
